// <auto-generated />
using CestNcm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CestNcm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628032335_AddMvaSubstituto")]
    partial class AddMvaSubstituto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CestNcm.Domain.Entities.ProdutoCest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cest");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("MvaAjustada12")
                        .HasColumnType("numeric")
                        .HasColumnName("mva_ajustada_12");

                    b.Property<decimal?>("MvaAjustada4")
                        .HasColumnType("numeric")
                        .HasColumnName("mva_ajustada_4");

                    b.Property<decimal?>("MvaOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("mva_original");

                    b.Property<decimal?>("MvaSubstituto")
                        .HasColumnType("numeric")
                        .HasColumnName("mva_substituto");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ncm");

                    b.Property<string>("Secao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secao");

                    b.HasKey("Id");

                    b.ToTable("produtos_cest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
